RK2 merge request.
java-park-mail-ru/joking-hazard-02-2017 pull request #3
Opened 2017-03-27 13:44 UTC by lieroz

1. Сервер переведен на работу с БД. Используется JDBC.

2. Появилась папка APITests, где тестируются запросы к API.

3. Тесты на регистрацию юзеров в папке UnitTests

4. Реальное приложение висит на heroku. Тесты и локальный запуск гоняются на H2 in-memory.

5. CI на travis - done. Даже работает.

6. @NotNull, @Nullable - вроде тоже с избытком.

2017-03-27 14:12 UTC, KSolovyev commented
Прежде всего, горящие инспекции почините

2017-03-28 18:58 UTC, KSolovyev commented
код весь зеленый. Вы наверное файлы перемещали. Поэтому я посмотрю его еще раз)

2017-03-28 19:27 UTC, KSolovyev requested changes

2017-03-28 19:27 UTC, KSolovyev commented on pom.xml
> +            <artifactId>spring-jdbc</artifactId>
это зачем? Предыдущей зависимости должно хватить

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Controllers/UserController.java
> +        if (body.getUserMail() != null) {
сделайте return сразу, пожалуйста
```
if (body.getUserMail() == null) {
    return...
}
```

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Controllers/UserController.java
> +                    break;
и тут. без брейков и локальных переменных. Просто сразу return

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Controllers/UserController.java
> +        if (form.getOldPassHash() != null && form.getNewPassHash() != null) {
return

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Controllers/UserController.java
> +                msg = messageSource.getMessage("msgs.forbidden", null, Locale.ENGLISH);
return, else тогда не нужен

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Controllers/UserController.java
> +                        resCode = true;
return

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/DAO/AccountDAO.java
> +                new UserData(
что будет в ответе пользователю в случае ошибки?

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Services/AccountService.java
> +        } catch (DuplicateKeyException ex) {
а если не такое исключение вылетит?

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Services/AccountService.java
> +        } catch (DuplicateKeyException ex) {
и это вопрос ко всем вашим  try...catch

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Views/LogInData.java
> +        return ViewError.OK;
что это?

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Views/MailForm.java
> +// Changed name to merge pull request
это, видимо, к делу не относится

2017-03-28 19:27 UTC, KSolovyev commented on src/main/java/sample/Controllers/UserController.java
> +        final UserInfoModel data[] = {null,};
почему это массив?? Да еще и такой странный?

2017-03-28 19:27 UTC, KSolovyev commented on src/main/resources/db/migration/V1__init.sql
> +);
индексы?

2017-03-28 19:27 UTC, KSolovyev commented on src/test/java/tests/APITests/ChangeMailIT.java
> +@RunWith(OrderedRunner.class)
мы вам такого не показывали
Тесты должны запускаться в одинаковых условиях. То, что вы написали - это один большой тест. Тесты в разных файлах запускаются не в гарантированном порядке. 
В общем сделайте на нормальном SpringRunner'е. С данными, которые остаются после надо что-то придумать

2017-03-28 19:27 UTC, KSolovyev commented on src/test/java/tests/UnitTests/TestRegistration.java
> +        assertSame(error, AccountService.ErrorCodes.OK);
опять же, эти тесты тоже должны стартовать в одинаковых условиях. Данные должны подготавливаться в методе `@BeforeClass`

2017-03-28 19:35 UTC, lieroz commented on src/test/java/tests/APITests/ChangeMailIT.java
> +@RunWith(OrderedRunner.class)
Вот непонятно в чем косяк. Нужно еще большее дробление на тесты? OrderedRunner наследуется от того же класса что и SpringRunner, только добавлена сортировка. Это сделоано для того чтобы гарантировать порядок выполнения тестов, иначе порядок установится лексически. А писать test1, test2 и т.д. это... ну такое себе.

2017-03-28 19:36 UTC, lieroz commented on src/test/java/tests/UnitTests/TestRegistration.java
> +        assertSame(error, AccountService.ErrorCodes.OK);
Данные подготавливаются в методе @BeforeClass и тесты запускаются с небольшими изменениями.

2017-03-28 19:36 UTC, lieroz commented on src/main/resources/db/migration/V1__init.sql
> +);
Серьезно? А зачем они тут?

2017-03-28 19:39 UTC, lieroz commented on src/main/java/sample/Controllers/UserController.java
> +        final UserInfoModel data[] = {null,};
Писалось не мной, но это сделано для того, чтобы JSON вернулся в виде
Object {
    field1: "somw_field",
    field2: [
               ]
}

2017-03-29 05:44 UTC, KSolovyev commented on src/test/java/tests/APITests/ChangeMailIT.java
> +@RunWith(OrderedRunner.class)
тесты должны работать в произвольном порядке. Они в больших системах вообще в несколько потоков запускаются. Каждый тест - отдельная проверка, никак не связанная с остальными. Когда я смотрю в упавший тест, мне не надо смотреть еще и все остальные, чтобы понять в чем дело. У меня есть гарантия, что он запускался на чистых данных

2017-03-29 05:44 UTC, KSolovyev commented on src/test/java/tests/UnitTests/TestRegistration.java
> +        assertSame(error, AccountService.ErrorCodes.OK);
не должно быть этих изменений

2017-03-29 05:45 UTC, KSolovyev commented on src/main/resources/db/migration/V1__init.sql
> +);
а вы разве не ищете пользователей по логину?

2017-03-29 05:46 UTC, KSolovyev commented on src/main/java/sample/Controllers/UserController.java
> +        final UserInfoModel data[] = {null,};
это же метод, возвращающий одного пользователя, нет?

2017-03-29 23:14 UTC, lieroz commented
Вроде исправил все замечания. Ну, я надеюсь.

2017-03-30 08:08 UTC, KSolovyev requested changes

2017-03-30 08:08 UTC, KSolovyev commented on src/main/java/sample/DAO/AccountDAO.java
> +                new UserData(
> что будет в ответе пользователю в случае ошибки?

2017-03-30 08:09 UTC, KSolovyev requested changes

2017-03-30 08:09 UTC, KSolovyev commented on src/main/java/sample/Services/AccountService.java
> +        } catch (DuplicateKeyException ex) {
> а если не такое исключение вылетит?
и это вопрос ко всем вашим try...catch

2017-03-30 08:10 UTC, KSolovyev requested changes

2017-03-30 08:10 UTC, KSolovyev commented on src/main/resources/db/migration/V1__init.sql
> +  password VARCHAR(50) UNIQUE
а вы запрещаете неуникальные пароли? =)

2017-03-30 10:09 UTC, KSolovyev requested changes

2017-03-30 10:09 UTC, KSolovyev commented on src/main/resources/db/migration/V1__init.sql
> +  password VARCHAR(50)
вот такие штуки нужно делать отдельным sql скриптом. Если уже выкатили версию с констрейном, то все, ее менять уже нельзя

2017-03-30 13:19 UTC, KSolovyev commented on src/main/resources/db/migration/V2__alter.sql
> +alter table users drop password;
был бы это реальный проект, в этот момент вы бы дропнули всем пользователям пароль

2017-04-01 12:08 UTC, merged