RK_3. Sorry V 2.0
java-park-mail-ru/joking-hazard-02-2017 pull request #4
Opened 2017-04-27 16:39 UTC by lieroz

Sorry :(

2017-04-27 17:10 UTC, duchuyctlk commented on src/main/java/sample/Game/Mechanics/Cards/CardDeck.java
> +        return card;
IMO we could write simply `return  container.remove(0);` bacause the method return the removed value.

2017-05-10 19:37 UTC, wolf1996 commented
Есть живые?

2017-05-17 08:53 UTC, KSolovyev requested changes
Сделайте реформат кода. Нужно чтобы методы отделялись от остального кода одной пустой строкой. Иначе очень сложно читать

2017-05-17 08:53 UTC, KSolovyev commented on src/main/java/sample/WebSockets/LobbySocketConfig.java
> +    /*@NotNull
надо убрать закомментированный код. Не только здесь, а везде

2017-05-17 08:53 UTC, KSolovyev commented on src/main/java/sample/Game/Services/ServerManager.java
> +    private ErrorCodes sendError(WebSocketSession session, String errorText){
ErrorCodes вы обрабатываете только в случае createGame. Либо пишити логику, которая что-то делает с errorCode, либо делайте остальные методы void

2017-05-17 08:53 UTC, KSolovyev commented on src/main/java/sample/Game/Services/ServerManager.java
> +    public class GameIndex{
static

2017-05-17 08:53 UTC, KSolovyev commented on src/main/java/sample/Game/Mechanics/MainMechanics.java
> +    public class GameContext{
слишком большой класс. Вынесите  его наружу

2017-05-17 08:53 UTC, KSolovyev commented on src/main/java/sample/Game/Mechanics/MainMechanics.java
> +    public enum  ErrorCodes{
Выглядит как message results, а не как error codes

2017-05-17 09:04 UTC, KSolovyev requested changes
Нужно расставить аннотации `@Override` там где вы переопределяете функции интерфейсов или абстрактных классов

2017-05-17 09:04 UTC, KSolovyev commented on src/main/java/sample/Game/Mechanics/MainMechanics.java
> +    public ErrorCodes handleMessage(BaseMessageContainer msg){
Вот тут будут гонки

2017-05-17 09:04 UTC, KSolovyev commented on src/main/java/sample/Game/Mechanics/States/InitState.java
> +            default:
Если мы получили тип сообщения, которое не ожидали, надо писать warn. И обязательно добавить текст самого msg

2017-05-17 09:04 UTC, KSolovyev commented on src/main/java/sample/Game/Mechanics/States/InitState.java
> +            default:
Ага, увидел обработчик. Но стоит все равно подумать, чтобы выводить msg

2017-05-17 09:04 UTC, KSolovyev commented on src/main/java/sample/Game/Mechanics/MainMechanics.java
> +    public class GameContext{
А еще расставьте final и volatile

2017-05-17 09:10 UTC, KSolovyev requested changes
Нужны тесты на игру

2017-05-17 09:11 UTC, KSolovyev commented
Добавьте в заголовок пул реквеста ссылку на фронт, пожалуйста

2017-05-18 12:23 UTC, wolf1996 commented on src/main/java/sample/Game/Mechanics/MainMechanics.java
> +    public ErrorCodes handleMessage(BaseMessageContainer msg){
Это место будет выполняться в одном потоке

2017-05-22 12:03 UTC, KSolovyev commented
давайте количество тестов игровых доведем хотя бы до 2-3 и тогда ок

2017-05-24 15:21 UTC, KSolovyev commented
парни, тесты?

2017-05-25 06:29 UTC, wolf1996 commented
Делал диплом, сейчас сделаю

2017-05-25 09:35 UTC, wolf1996 commented
Добавил питонические тесты, в travis добавлять?

2017-05-25 10:27 UTC, KSolovyev commented
да, давай

2017-05-25 14:10 UTC, KSolovyev requested changes

2017-05-25 14:10 UTC, KSolovyev commented on src/main/java/sample/Game/Services/ServerWorker.java
> +    private static class KeyGenerator {
Wat dat?

2017-05-25 14:10 UTC, KSolovyev commented on src/main/java/sample/Game/Services/ServerWorker.java
> +            if(!this.messageQue.isEmpty()){
while, наверное

2017-05-25 16:54 UTC, merged