Рк4
java-park-mail-ru/joking-hazard-02-2017 pull request #6
Opened 2017-05-25 19:48 UTC by wolf1996

2017-05-28 10:32 UTC, isopov commented
Начнём потихоньку:
`1. Deprected-классы стоит уважать, тем более когда это так просто (ваше общение с Dropbox) - `DbxRequestConfig dbxRequestConfig =DbxRequestConfig.newBuilder("dropbox").withUserLocale("en_US").build()` вместо `DbxRequestConfig dbxRequestConfig = new DbxRequestConfig("dropbox", "en_US");`
2. dropbox.properties - вы всем показали ключ доступа к своему dropbox - я правильно понимаю?
3. Что за хрень с тестами? Объяснитесь, зачем вам бесконечные "интеграционные тесты" и вообще нет обычных тестов? (Я думал интеграционные у вас на питоне) - пофиксите чтобы они заканчивались, и переделайте на максимально обычные - ничего интеграционного в них нет
4. `} catch (IOException ignored) {}` - не делайте так никогда - либо логируйте, либо пробрасывайте, либо в самом крайнем случае оставляйте вместо обработчика комментарий
5. `e.printStackTrace();` - такое всё удалите - логирование имеется в виду в логгер
6. Через вашу многопоточную логику сложно пробиться - много неиспользуемого. Либо удалите, либо как-то заиспользуйте. Непонятно почему очереди сообщений создаются в ServerManager, а не прямо в ServerWorker, если они там не используются. Очередь системных сообщений сейчас не используется. Executor-ы в ServerManager складываются в неиспользуемый список - зачем? ObjectMapper создаётся свой, а не берётся с спрингового контекста. maxThreads переменная имеет всегда одно значение - почему это не контанта (только тогда сделайте её поменьше - или вынесите это в конфигурацию, но тоже с меньшим значением по-умолчанию - 2 это уже многопоточность)
7. Класс Vector не используйте, пожалуйста. ImmutableList из гуавы, раз уж вы её подключили, или Collections.unmodifiableList, или в случае, которого я пока не вижу, когда вам нужен изменяемый потокобезопасный список - CopyOnWriteArrayList или Collections.synchronizedList(new ArrayList<>());

2017-05-28 10:51 UTC, wolf1996 commented
Можно поправить после первого числа?

2017-05-28 10:53 UTC, lieroz commented
Как понять бесконечные тесты? И куда надо убрать ключ, чтобы его не было видно? При старте прописывать как один из параметров запуска?

2017-05-28 12:22 UTC, isopov commented
>Можно поправить после первого числа?

Крайний срок - 3 число.

> Как понять бесконечные тесты?

У меня они перед стартом (что из консоли через mvn integration-test, что из Идеи) они зависают, сжирая все 4 ядра на 100%

> И куда надо убрать ключ, чтобы его не было видно? При старте прописывать как один из параметров запуска?

Например так. Или в переменной окружения. Или вообще убрать из репозитория и сборки и подгружать боевые настройки снаружи jar-ника.

2017-05-30 10:28 UTC, KSolovyev requested changes

2017-05-30 10:28 UTC, KSolovyev commented on src/main/java/sample/Game/Services/ServerManager.java
> +            ScheduledExecutorService new_executor = Executors.newScheduledThreadPool(1);
camelCase plz

2017-05-30 10:28 UTC, KSolovyev commented on src/main/java/sample/Game/Services/ServerManager.java
> +        executor = new ArrayList<>();
`executors` plz

2017-05-30 10:28 UTC, KSolovyev commented on src/main/java/sample/Game/Services/ServerManager.java
>          maxThreads = 5;
в константы

2017-06-03 07:20 UTC, isopov commented
Ну, конечно, осталось много слишком явных огрехов.
1. Зачем вы наворотили таких тестов я так и не понял - попробовал всё ваше удалить и переделать в обычные - всё работает. Я этого от вас уже просил.
2. Локализация хороша))
3. Guava подключена для одного исопльзования, которое можно заменить на простое `final URL fl = ResourceManager.class.getResource("/Property");`
4. Куча `SuppressWarnings` - инспекции не для того, чтобы их подавлять, а чтобы подсказать вам как надо исправить ;-)

P.S. Прямо во время защиты править ничего не надо!

2017-06-03 07:20 UTC, merged